In [12]:
import torch
#switch to parallel processing 
#device = 'cuda' if torch.cuda.is_available() else 'cpu'
#print(device)
#Ingrated GPU: force PyTorch to use the CPU for computations, which is the appropriate choice for systems without a dedicated GPU.
#it should run without trying to access CUDA resources.
device ='cuda'if torch.cuda.is_available() else 'cpu'
print(device)

block_size = 8
batch_size = 4 #No of blocks in parallel


cpu


In [2]:
with open('wizard_of_oz.txt', 'r',encoding ='utf-8') as f:
    text = f.read()
print(len(text))
print(text[:200])

232272
DOROTHY AND THE WIZARD IN OZ

BY

L. FRANK BAUM

AUTHOR OF THE WIZARD OF OZ, THE LAND OF OZ, OZMA OF OZ, ETC.

ILLUSTRATED BY JOHN R. NEILL

BOOKS OF WONDER WILLIAM MORROW & CO., INC. NEW YORK


[Ill


In [3]:
chars = sorted(set(text))
print(chars)

['\n', ' ', '!', '"', '&', "'", '(', ')', '*', ',', '-', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '\ufeff']


In [7]:
string_to_int = { ch:i for i,ch in enumerate(chars) }
int_to_string = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [string_to_int[c] for c in s]
decode = lambda l: ''.join([int_to_string[i] for i in l])\

print(encode("hello"))
encoded_hello=encode("hello")
decoded_hello=decode(encoded_hello)
print(decoded_hello)

data 

[61, 58, 65, 65, 68]
hello


tensor([80, 28, 39,  ...,  0,  0,  0])

In [6]:
data = torch.tensor(encode(text),dtype=torch.long)
print(data[:100])

tensor([80, 28, 39, 42, 39, 44, 32, 49,  1, 25, 38, 28,  1, 44, 32, 29,  1, 47,
        33, 50, 25, 42, 28,  1, 33, 38,  1, 39, 50,  0,  0, 26, 49,  0,  0, 36,
        11,  1, 30, 42, 25, 38, 35,  1, 26, 25, 45, 37,  0,  0, 25, 45, 44, 32,
        39, 42,  1, 39, 30,  1, 44, 32, 29,  1, 47, 33, 50, 25, 42, 28,  1, 39,
        30,  1, 39, 50,  9,  1, 44, 32, 29,  1, 36, 25, 38, 28,  1, 39, 30,  1,
        39, 50,  9,  1, 39, 50, 37, 25,  1, 39])


In [8]:
n = int(0.8*len(data))
train_data = data[:n]
val_data = data[n:]

In [9]:
x = train_data[:block_size]
y = train_data[1:block_size+1]

for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print("When input is", context, "target is", target)

When input is tensor([80]) target is tensor(28)
When input is tensor([80, 28]) target is tensor(39)
When input is tensor([80, 28, 39]) target is tensor(42)
When input is tensor([80, 28, 39, 42]) target is tensor(39)
When input is tensor([80, 28, 39, 42, 39]) target is tensor(44)
When input is tensor([80, 28, 39, 42, 39, 44]) target is tensor(32)
When input is tensor([80, 28, 39, 42, 39, 44, 32]) target is tensor(49)
When input is tensor([80, 28, 39, 42, 39, 44, 32, 49]) target is tensor(1)


In [11]:
 n = int(0.8*len(data))
train_data = data[:n]
val_data = data[n:]

def get_batch(split):
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

x, y = get_batch('train')
print('inputs:')
# print(x.shape)
print(x)
print('targets:')
print(y)

inputs:
tensor([[78, 68, 74,  1, 76, 71, 68, 67],
        [ 1, 54, 73,  1, 54,  1, 75, 58],
        [33, 43,  1, 42, 39, 39, 37, 24],
        [68, 57, 62, 58, 72,  1, 68, 59]])
targets:
tensor([[68, 74,  1, 76, 71, 68, 67, 60],
        [54, 73,  1, 54,  1, 75, 58, 67],
        [43,  1, 42, 39, 39, 37, 24,  3],
        [57, 62, 58, 72,  1, 68, 59,  1]])


In [ ]:
import torch.nn as nn
from torch.nn import functional as F

class BigramLanguageModel(nn.Module):
    def __init__(self, vocab_size):
        super.__init__()
        self.token_embedding_table = nn.Embedding(vocab_size.vocab_size)
        #matrice x and y represent vocab size
        
    def forward_pass( )